### ISSUE TITLE
Layout/SpaceInsideBrackets

### ISSUE THREAD

**Issue by thomthom** [pocke/mry#34]
I came across another cop that didn't migrate:

```yml
Layout/SpaceInsideBrackets: 
  Enabled: false 
```

I manually migrated that to:

```yml
Layout/SpaceInsideArrayLiteralBrackets: 
  Enabled: false 
```

I didn't see any Hash variant of this. Seems like a straight forward migration.

**Comment by pocke** [comment]
:eyes:

**Comment by pocke** [comment]
https://github.com/bbatsov/rubocop/pull/5149
`Layout/SpaceInsideBrackets` has been separated to `Layout/SpaceInsideArrayLiteralBrackets` and `Layout/SpaceInsideReferenceBrackets` in this pull-request.

So we can apply the same approach as #33 to the cops.
