### ISSUE TITLE
Missing Linux executable

### ISSUE THREAD

**Issue by deric** [pocke/mry#51]
In order to work on Linux there should be an executable `bin/mry` file (not just in `exe/mry`).

**Comment by pocke** [comment]
`exe/` directory doesn't mean Windows and `bin/` directory doesn't mean Linux.
Mry uses `exe/` for executable files that are published as a gem package. So you can use `mry` command if you execute `gem install mry`.
And Mry uses `bin/` for internal tools. For example, `bin/setup` setups development environment for Mry. This directory is not exposed to the gem package.

We can confirm it with this configuration. https://github.com/pocke/mry/blob/4d74760c6085d50b067f83fde3596fb85ab5ce25/mry.gemspec#L23 


Thanks for reporting the issue.
If you have any questions, feel free to comment on this issue.
